# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V

script: ./travis/publish.sh
# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "sj0i2ehlHwiqAzneTSLtu+yo5QOU4x1OsfRGUDN90WEluKri5PYC/WKy8dp1FJrTe7fLBfNf1Cl4apVJ5Wbb+pan3stuTmMp660fxv7KU+BKCwlno8tiGkJjBb+kK6WtxvNpGDqTw/Y7bMzptEytiKsYhkpd637UmsAIQm0ObK1qjEshkVpVI6/5bBS1HkwE9wZNdSq16phk8ZS1MxxCYNeQJPWhtD7D1iivv8rv65ucANj2aAAyf52hq100Zsm85/7z2QgZ0pBMEgPAqju5kIZpl9Ww+wtT/Y84KFGA/9ioWc0VxPu9eKKjmP6+JDJGZ1i6LMrqboyqhrUd+sfL7TRQFyc6+z+9ASzj+Rq9s+XJWp9YAQofv/sJxmZg7cLiYtDBwHYqzkgDRgDjTKjpSW6cLwoH1F2SVA+1CDtoBiW2ccZ+FDJ35Kyv6FY4+GLb0qtffCwNsQavhMUHyKEh3sXzp0ZT1YGW2/ylmqmrlr3j8nc7F1YkYEeVwZ3j0UbZj+/RGSsG2A8ldeu5jO0iTKSIzO68vexeFQFFPHZha/2aqWkGiqkYg8NtasbEwzH3uSydq7Fa41BqOkNvldK2k4n5Zlq5QetaSMaVhR4rHQgQ14k3GjwzHjruFuqN/wmDPpBS6Pczie+heyeqEeM852pDsybpBsSeae6p7qJqXm0="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "eB2I9UWkpagmt5iYMnVlIGGe/slNf9iJrF/7PiAptjhNvc1u+z7vWkPEl66YdBPqpCFMfhbIaJVO6gTtCTEPBaigOKMdHQmjkncKbVTmpNLyEfLU3nkrSR+Q+64uN/E65puhYHdYYgGwacFfz/nN8CVXrfwp9UBOo3d5M4AQQvcPf+cOG+Ba2+cQQH+CGNcUELj5EmamuENZtdtMq3DbEmvkYwzc4RPFpi0j7ErzzLHD6xvMTyHaC9obx9wspcDiR0Wrlfcy5z92jgx3shFHcvOUCV5XpjkqN3/NTJqEbE8bF54JNs4UwxC1y8m3kURRCpGSIEa9ktDmgW6tvFbHD/kHBOw9O5w520d8ajuaZX0Fs18uJ3cEsKUD1QklUp+5soi4904hkS4RzxPjd7SpWvijN+sNTxzmf90Y/83nzAhHinuKJKvPNSZDr2eYXPCziydQltTTV35NVyCfxJNj9Hzp6wDR4UUqrJkxNP8rrxwdeXp+xFEohAIGnaaWkvFPCN7svMl2J+rBL6Rn8rYmQzrjQmsZixM7In5EJNGAd0IgFT1rJXOWr7klRTCuewuiwg4VHQO9eTbGSikHlXSsiHhxxPWLzfnZsnsu0U9IoGt/PZfMW7bdcigj/r7A0+WuPkK8MISgs4O3204z/xSq3v3kWjuyFSOhHLS03kBf+sg="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "hJdW5pjVbDlm9Um1VoZ6/NVf46XCXmOwpXXOpJsNoyoWyoivcpx9GoXAS5RN5YZhZMzWPRxkmChPzts0HiCKxmK3M1F95O8V3Me+qNqkBYceS7++w9bThBOO1ky0HB0Kz4TPRqIzCBVRGwlF3ZA27pl+byO14tVS4JDJAD9vGwbs9CNe+CpBreBIdfm4oxgRRLODU8rG1PzW7hnNDavow62hNI2mf0NrvEB4wcpe+XHNa69vQUQV+QtxH/x1K9BbIw97iANXR3zlytTVV2lza4mWDDHBa0htFzOlGEI6k+S1dPGDlIa441ahbx1b6nFyiHyXgSErvHUn8gxYLIcrF7ml8ELP0yCD4iZfj/7ZyEqPcGQ4iot/FgG3o3LzwbYo0BwCy3Rio48y7Kxg6EY79RJ3BWNmXO/pyxbQXAHPvjfPn7K8L0R/vlVgFquSViPc/Um0nB/GxNxiiDze+fRJDTR0j7lubxHAKDfhHXytrq8Alzhm4LBWQToxHkUKkPCtvcX/6xvYcMAPXgteF8ryKiT/AZKX2MJjx637bsZQcrGA73rtR1d3oj0sXo5DzArMoCdmNaoSy1zog9kXJ05+4kKgQqiMXfPAQ88l4R07sC78WmcHzKf+RPGUizsgV1pa9fu7voPjzAfsVsIKUMZbk9iMeYgF6vAtfW6d4Zd7P08="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "yFvPUjctLNJuWAdImD9tbk6G+ESXHuUPdCNxddXH4QsHN2mLu2fJkisqhuEPBvWjkTW1Ej+/HPDp9TsirarPAk/s0TfWx/NIKiwIfcgCgSNzNrBlSCRoX7cX9FU3Bu3LI8N0s0U7i0dzTvErY8kcqr3QE3MsBxKxbXhU1cZTw6LvAo8ay5bk9mkuIB43mSODKWqGx6sqOCt/HFuEoDA4Xr5iCqGHNxZobqB+TdsPdetUIJRFT8J8FxmrR0k+XSoZPHjECvCCcPI4f1Nl6SESrfMs8qbjCMjjVz3kwLaJxgthaj6MA8Iq0SQk1hXuUogkobMp7j0qoPUV1pIWL9r7kQ2iIOlLDreBXBsWHEQxZrYlCCICBWk/E1XkqTos2wd9SAl9zps+8lONhoxLeQbwRLnWCG0gmX5t7pXX1/Xz97WDc0QpWczC61mxSPkJ1FBT+qtesWk8xcsVrp8Tp/Mmd65rNTTx3UBN0/zd03DNYwoOch2UlN7sfRJAjKNxJzbD6WLul6YTlV1ElRI+cAT+kqz78477SUof/ZGf+rt+UBbcAhddomgEnlaBQb6m88OJCLYilg5sq9EATRqcTxrRGN0GnERsUXC73FoQzKQQojBK5tSxcCl+kTdoi4z26lXPd76qzZJvCLB7RgRlougj934v6np/wuF6sszmvQyqccE="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "F6OU32QnBEYpkJBqfzb9pmgynWDgHBz49sTCTvqoRvJK479Lvczbq7QWxXIUXjNU6gaj081veluoJm6yuagYBSTpz8Ky6JRbN68eNxJXQZ3eYokyHkbgbs24Y0kjHKyRVEOErdNGU2Otnnw0k2L9y+ccKnn9NTsv0VHHw6cok69LnJB2I7n5vLx4Ll13dQjiAN5/UJHGoqqkWkyJKDKd42OANYwGHoumtC9DDdmOZqtJpnwHEBg/s0iQYd0KoPUG+Pyo4U95XpSvDyavUoUMToLVbMOcxh820LpD1QSFXFoNUqgZWZHGBLwafy+bQ4SxhSt+sTSgd3c6FmKlVT+OqLtbAEa2Z97mdlEUYGWoOyGBnpse8RdcMdeWvyHCwhmMHRqd5/Xqz8+LPaELl7mu+ghIZNJHnMgXCzxarSmh2te0iVi+Cqt0Rz6Uyxgo8JIdiQBFvpjdnsavW50AeT++bkKp3pRe2bCJHEY40SnJsUz5NjruA2qHIJm0x6AGYJMlAB8tigqeMOGSWMx4cOR8riyf3ZY4CPbvy5zGr2XWVsn2MOU7FZEOgwSnC8oZVNX2O67ZP2ercBBrnzmdFOMBM9tqUpUNL2bW71sqBPY6xvo/DbmMfhOsHLSyNtYHWyMNWT2a9r+0CSn8VX8m+2OR2Fpbui6kOQ/IAiBJrMu8DIQ="

